name: ironcirclesapp
description: cross platform ironcircles app
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning


# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.36+159

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter


  #flutter team
  audioplayers: ^6.1.0
  google_fonts: 6.1.0
  cupertino_icons: 1.0.8
  http: 1.2.2 #^0.12.2
  image_picker: 1.1.2 #^0.8.6+1 #^0.8.5+3  #NO DESKTOP SUPPORT
  path_provider: 2.1.5 #^2.0.1
  shared_preferences: 2.5.2 #^0.5.4+1
  url_launcher: 6.3.1 #^6.0.3
  url_launcher_android: 6.3.15
  firebase_messaging: 15.2.0 #^14.2.2 #NO DESKTOP SUPPORT FOR WINDOWS
  firebase_core: 3.10.0 #^2.7.0 #^1.7.0 #NO DESKTOP SUPPORT FOR WINDOWS
  intl: ^0.19.0
  video_player: 2.9.3 #^2.4.7
  video_player_android: ^2.8.2
  #connectivity: ^3.0.3 #discontinued
  connectivity_plus: 6.0.5
  camera: 0.11.1 #0.10.5+9 #^0.9.8+1
  scrollable_positioned_list: 0.3.8 #^0.2.3
  cross_file: 0.3.4+2 #All
  in_app_purchase: 3.2.1 #3.1.13
  path: 1.9.1 #1.8.3 #1.8.2
  sqflite_common_ffi: 2.3.5
  
  #pay: ^1.0.11
  #webview_flutter: ^2.0.12


  #fluttercommunitydev
  rxdart: 0.27.7 #^0.26.0-nullsafety.1
  share_plus: 10.1.3 #7.2.1 #^4.0.10+1
  chewie: 1.11.2 #^1.5.0 #1.3.5

  #other open source
  permission_handler: 11.3.1 #^10.0.0
  permission_handler_android: 12.0.13
  flutter_secure_storage: 9.2.2 # //ALL PLATFORMS
  sqflite: 2.4.2 #^2.0.0+3 #NO DESKTOP SUPPORT FOR WINDOWS (maybe)
  flutter_linkify: 6.0.0 #4.0.2
  flutter_local_notifications: 17.2.2 #16.3.0 #^9.1.4 #^5.0.0+1 #^3.0.1+2
  dio: 5.5.0+1 #5.4.0
  uuid: 4.3.3
  flutter_image_compress: 2.1.0 #^0.7.0
  photo_view: 0.15.0 #^0.11.1 #^0.9.2
  avatar_glow: 3.0.1 #^1.2.0
  flutter_spinkit: 5.2.0 #^4.1.2+1
#  receive_sharing_intent:
#    git:
#      url: https://github.com/KasemJaffer/receive_sharing_intent
#      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  #receive_sharing_intent: 1.8.1
  receive_sharing_intent:
    git:
      url: https://github.com/ironcircles/receive_sharing_intent
      ref: 51cdfed6b1bccaf6516c575048b184023e5eac07
  provider: 6.1.2 #^5.0.0-nullsafety.
  image: 4.1.3 #^3.0.2 #ALL PLATFORMS
  flutter_colorpicker: 1.1.0 #^0.5.0
  #video_thumbnail: 0.5.3 #^0.5.2 #^0.4.6
  get_thumbnail_video: 0.7.3
  percent_indicator: 4.2.3 #^3.0.1 #^2.1.8
  pattern_lock: 2.0.0 #^1.0.3
  file_picker: 9.1.0 #8.1.6 #8.0.2 #6.1.1
  cryptography: 2.7.0
#  hive: 2.2.3 #TODO remove
#  hive_flutter: 1.1.0  #TODO remove
  ndialog: 4.4.1+1 #^3.2.1  #progress dialog  #ALL
  cached_network_image: 3.3.1 #^3.1.0  #No Windows
  flutter_inappwebview: 6.1.5 #^5.4.3+7 #No MacOS or Windows
  #image_cropper: 5.0.1 #No MacOS or Windows
  #launch_review: 3.0.1   #No MacOS or Windows
  store_redirect: 2.0.4
  toggle_switch: 2.2.2 #All
  multi_select_flutter: 4.1.3 #ALL
  pin_code_fields: 8.0.1  #ALL
  flutter_native_splash: ^2.3.9
  table_calendar: 3.1.1
  maps_launcher: 3.0.0+1
  #media_scanner_scan_file: ^0.0.4
  tutorial_coach_mark: 1.2.11
  firebase_dynamic_links: 6.1.0
  #flutter_quill: 9.4.1
  flutter_staggered_grid_view: 0.7.0
  mime: 2.0.0 #^1.0.4
  flutter_pdfview: 1.3.2
  #flutter_sliding_up_panel: ^2.1.1
  animated_text_kit: 4.2.2
  emoji_picker_flutter: 4.3.0
  http_parser: 4.0.2
  #bitmap: ^0.2.0
  media_kit: 1.1.11 #support linux and windows video playing
  media_kit_video: 1.2.5
  media_kit_libs_video: 1.0.5
  #image_compression_flutter: ^1.0.4 #support getting a thumbnail in windows and linux
  crop_image: 1.0.12 #support cropping in windows and linux
  fc_native_video_thumbnail: 0.17.2
  sqflite_sqlcipher: 3.1.0+1
  msix: 3.16.7 #Windows installer
  device_info_plus: 11.3.3
  flutter_reorderable_grid_view: 4.0.0
  windows_taskbar: 1.1.2
  sha3: 0.2.0
  integer: 1.0.0
  pasteboard: 0.2.0
  desktop_drop: ^0.4.4
  convert: 3.1.2
  background_downloader: 9.2.0 #8.9.3
  flutter_background_service: 5.1.0
  flutter_plugin_android_lifecycle: 2.0.22
  image_picker_android: 0.8.12+22
  #agora_rtc_engine: ^6.5.2
  #agora_uikit: ^1.3.10

  #open_file: ^3.3.1
  #wakelock: ^0.6.2

dependency_overrides:
  intl: 0.19.0
#TODO temporary overide because the flutter yahoos broke the camera on Android 13
#dependency_overrides:
  #camera_android:
    #git:
      #url: https://github.com/elmar001/plugins.git
      #path: packages/camera/camera_android
      #ref: 5172b44088a4082ff0899594614c5380457d341b

#dependency_overrides:
#    sqflite:
#      git:
#        url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
#        path: sqflite
#        ref: fmdb_override

dev_dependencies:
  #screenshot_callback:
   # git:
    #  url: git://github.com/ousvat/flutter_screenshot_callback.git
  flutter_launcher_icons: "^0.13.1"
#  hive_generator:
#    git:
#      url: https://github.com/hivedb/hive.git
#      path: hive_generator
  build_runner: ^2.1.0 #^1.12.0
  flutter_lints: ^3.0.1


flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_trim.png

msix_config:
  display_name: IronCircles
  msix_version: 1.0.0.0
  app_installer: #<-- app installer configuration
    publish_folder_path: c:\proj\windowsinstall
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: false
    show_prompt: true
    force_update_from_any_version: true
  publisher_display_name: IronCircles Inc
  logo_path: c:\proj\ironclient\assets\images\windows.ico
  #certificate_path: c:\proj\icinstallcert.pfx
  #certificate_password: iccert

flutter_launcher_icons:
  #android: "ic_launcher"
  android: false
  ios: false
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ios_icon.png"
  windows:
    generate: true
    image_path: "assets/images/windows.ico"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path:  "assets/images/ios_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/images/
    - assets/images/models/
    - assets/images/appstore.png
    - assets/images/avatar.jpg
    - assets/images/black.jpg
    - assets/images/ddg.png
    - assets/images/giphy3.png
    - assets/images/ic_launcher.png
    - assets/images/iron.jpg
    - assets/images/ironlight.jpg
    - assets/images/nopreview.jpg
    - assets/images/noimage-light.png
    - assets/images/noimage.png
    - assets/images/otv.png
    - assets/images/white.jpg
    - assets/images/ios_icon.png
    - assets/images/windows.ico
    - assets/images/landing.png
    - assets/images/vault.jpg
    - assets/images/ironcoin.png
    - assets/images/android_walkthrough/1.png
    - assets/images/android_walkthrough/2.png
    - assets/images/android_walkthrough/3.png
    - assets/images/android_walkthrough/4.png
    - assets/images/android_walkthrough/5.png
    - assets/images/android_walkthrough/6.png
    - assets/images/android_walkthrough/7.png
    - assets/images/android_walkthrough/8.png
    - assets/images/ios_walkthrough/1.png
    - assets/images/ios_walkthrough/2.png
    - assets/images/ios_walkthrough/3.png
    - assets/images/ios_walkthrough/4.png
    - assets/images/ios_walkthrough/5.png
    - assets/images/ios_walkthrough/6.png
    - assets/images/ios_walkthrough/7.png
    - assets/images/ios_walkthrough/8.png


